# Generated by Django 3.2.8 on 2021-10-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=255)),
                ('wicket', models.IntegerField(max_length=255)),
                ('vs', models.CharField(max_length=255)),
            ],
        ),
    ]
