# Generated by Django 3.2.8 on 2021-10-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='wicket',
            field=models.IntegerField(),
        ),
    ]
