# Generated by Django 3.2.8 on 2021-10-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_alter_score_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='wicket2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
